simulator first version
epfml/DeAI pull request #24
Opened 2020-12-18 13:02 UTC by ThomasDCepfl

Dear all,
Here is a first version of the simulator I have been working on throughout my semester project at MLO.
I tried to make it as generic and easy-to-use as possible.
I split the different aspects into different packages, which all have their dedicated notebook, Python files and README. 
I am open to any suggestions or remarks.
Best,
Thomas

2020-12-23 13:39 UTC, koloskova requested changes
The code looks good and implements many useful features, however, the code structure could be improved. There are many repetitions in the code which are good to be avoided.

2021-01-04 10:00 UTC, IamTao commented on simulator/A-NC/A_NC.py
> +from utils import *
it is better to explicitly list the functions/classes names.

2021-01-04 10:02 UTC, IamTao commented on simulator/A-NC/A_NC.py
> +        epochs (int): the number of optimization steps between each communication (minimum 1)
the `epoch` here is confusing. is it correspond to the number of local update steps?

2021-01-04 10:05 UTC, IamTao commented on simulator/A-NC/A_NC.py
> +        diffuse_params(client_models, comm_matrix)
maybe `diffuse_params` could be a class that can provide different choices of diffusion, e.g. with compressed communication?

2021-01-04 10:06 UTC, IamTao commented on simulator/A-NC/README.md
> +# A-NC
it is a bit hard to infer the exact meaning of `A-NC`

2021-01-04 10:12 UTC, IamTao commented on simulator/A-NC/utils.py
> +    return loss.item()
in addition to the loss, we may need to track other metrics, e.g. top-1 acc?
also, right now, it seems like the function will only return the loss value of the last iterate. I think it is not sufficient?>

2021-01-04 10:13 UTC, IamTao commented on simulator/failures/utils.py
> +    cos = nn.CosineSimilarity(dim=0, eps=1e-6)
why we initialize the `cos` here?

2021-01-04 10:15 UTC, IamTao commented on simulator/failures/utils.py
> +    else: # distribution == 'non-iid'
we may include more description details and other degrees of non-iid-ness for the `non-iid` data distribution.

2021-01-04 10:18 UTC, IamTao commented on simulator/A-NC/utils.py
> +class Net(nn.Module):
agreed

2021-01-04 10:26 UTC, IamTao commented
the simulator code looks good to me. 

my main concern is that, why not build a unified simulation code (i.e., one package) that can cover different cases, e.g., topologies, failures, latency?

2021-04-19 19:38 UTC, merged